_BASE_: "./Base-BoundaryFormer-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
  ROI_MASK_HEAD:
    NAME: "BoundaryFormerPolygonHead"
    POOLER_TYPE: ""
  RETINANET:
    NUM_CLASSES: 2
  BOUNDARY_HEAD:
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    PRED_WITHIN_BOX: True
    POLY_NUM_PTS: 64
    CLS_AGNOSTIC_MASK: True
    POLY_LOSS:
      NAMES: ["MaskRasterizationLoss", "PolySmoothnessLoss"]
      WS: [1.0, 2.0]

  DIFFRAS:
    RESOLUTIONS: (64, 64, 64, 64, 64, 64, 64, 64)
    USE_RASTERIZED_GT: False
    INV_SMOOTHNESS_SCHED: (0.1,)

    POLY_SMOOTH_LOSS_WEIGHT_TYPE: 'linear'

  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    PROPOSAL_ONLY_GT: False
    NUM_CLASSES: 2
    NMS_THRESH_TEST: 0.5
  RPN:
    NMS_THRESH: 0.7
SOLVER:
  OPTIMIZER: "ADAM"
  BASE_LR: 1e-5
  WEIGHT_DECAY: 0.05
  WEIGHT_DECAY_NORM: 0.0
  STEPS: (25000, 35000)
  MAX_ITER: 40000
  IMS_PER_BATCH: 8
  CLIP_GRADIENTS:
    ENABLED: False
  CHECKPOINT_PERIOD: 2000
DATASETS:
  TRAIN: ("af_data_bubble_train",)
  TEST: ("af_data_bubble_test",)
VIS_PERIOD: 0
TEST:
  EVAL_PERIOD: 40000

